CREATE TABLE IF NOT EXISTS proyectos_areas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(80) NOT NULL UNIQUE,
  nombre VARCHAR(140) NOT NULL,
  accent VARCHAR(30) NOT NULL DEFAULT 'blue',
  orden INT NOT NULL DEFAULT 0,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proyectos_secciones (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  area_id INT UNSIGNED NOT NULL,
  slug VARCHAR(80) NOT NULL,
  nombre VARCHAR(140) NOT NULL,
  orden INT NOT NULL DEFAULT 0,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_area_slug (area_id, slug),
  CONSTRAINT fk_proyectos_secciones_area
    FOREIGN KEY (area_id) REFERENCES proyectos_areas (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS proyectos_items (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  section_id INT UNSIGNED NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  prioridad_key VARCHAR(30) NOT NULL DEFAULT '',
  prioridad_label VARCHAR(40) NOT NULL DEFAULT '',
  responsable VARCHAR(120) NOT NULL DEFAULT '',
  inicio VARCHAR(40) NOT NULL DEFAULT '',
  cierre VARCHAR(40) NOT NULL DEFAULT '',
  avance_planeado DECIMAL(5,2) NOT NULL DEFAULT 0,
  avance_real DECIMAL(5,2) NOT NULL DEFAULT 0,
  indice_diamante DECIMAL(5,2) NOT NULL DEFAULT 100,
  beneficio_principal TEXT NULL,
  status_key VARCHAR(40) NOT NULL DEFAULT 'blank',
  status_label VARCHAR(60) NOT NULL DEFAULT 'Pendiente',
  orden INT NOT NULL DEFAULT 0,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_section_order (section_id, orden),
  CONSTRAINT fk_proyectos_items_section
    FOREIGN KEY (section_id) REFERENCES proyectos_secciones (id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
