<?php

declare(strict_types=1);

$avevaConfig = require __DIR__ . '/../secadores-temperatura/config.php';

return [
  'titulo' => 'Concentradores',
  'timezone' => 'America/Mexico_City',
  'intervalo_actualizacion_ms' => 60000,

  'sqlserver' => (array)($avevaConfig['sqlserver'] ?? []),
  'tabla_aveva' => (string)($avevaConfig['tabla'] ?? 'TREND001'),
  'campo_fecha_aveva' => (string)($avevaConfig['campo_fecha'] ?? 'Time_Stamp'),

  'mysql_105' => [
    'host' => '192.168.1.105',
    'port' => 3306,
    'dbname' => 'progel_procesos',
    'user' => 'user_pro',
    'pass' => 'Pr0g3l2025PR',
    'charset' => 'utf8mb4',
    'timeout' => 3,
  ],
  'tabla_datos' => 'datos_concentradores',
  'columna_tipo' => 'tipo',
  'columnas_orden' => ['id_datos_hora', 'fecha_hora', 'fecha', 'created_at', 'updated_at', 'id'],

  'concentradores' => [
    'concentrador_1' => [
      'nombre' => 'Concentrador 1',
      'tipo' => 'Conc1',
      'flujo_field' => 'FLUJO_CONCENTRADOR_2',
    ],
    'concentrador_2' => [
      'nombre' => 'Concentrador 2',
      'tipo' => 'Conc2',
      'flujo_field' => 'FLUJO_CONCENTRADOR_3',
    ],
    'concentrador_3' => [
      'nombre' => 'Concentrador 3',
      'tipo' => 'Conc3',
      'flujo_field' => 'FLUJO_CONCENTRADOR_4',
      'metric_fields' => [
        'vacio' => 'VACIO_CONCENTRADOR_3',
      ],
      'metricas_extra' => [
        'corriente_concentrador' => [
          'label' => 'Corriente',
          'source' => 'sqlserver',
          'field' => 'CORRIENTE_CONCENTRADOR_3',
          'unit' => 'A',
          'decimals' => 2,
        ],
        'frecuencia_moyno' => [
          'label' => 'Frec. Moyno',
          'source' => 'sqlserver',
          'field' => 'FRECUENCIA_MOYNO_CONCENTRADOR_3',
          'unit' => 'Hz',
          'decimals' => 2,
        ],
        'corriente_moyno' => [
          'label' => 'Corr. Moyno',
          'source' => 'sqlserver',
          'field' => 'CORRIENTE_MOYNO_CONCENTRADOR_3',
          'unit' => 'A',
          'decimals' => 2,
        ],
        'presion_vapor' => [
          'label' => 'Presión Vapor',
          'source' => 'sqlserver',
          'field' => 'PRESION_VAPOR_CONCENTRAADOR_3',
          'unit' => '',
          'decimals' => 2,
        ],
        'setpoint_presion_vapor' => [
          'label' => 'SP Pres. Vapor',
          'source' => 'sqlserver',
          'field' => 'SETPOINT_PRESION_VAPOR_CONCENTRADOR_3',
          'unit' => '',
          'decimals' => 2,
        ],
        'apertura_valvula_vapor' => [
          'label' => 'Apert. Válvula',
          'source' => 'sqlserver',
          'field' => 'APERTURA_VALVULA_VAPOR_CONCENTRADOR_3',
          'unit' => '%',
          'decimals' => 2,
        ],
        'flujo_entrada_caldo' => [
          'label' => 'Flujo Caldo',
          'source' => 'sqlserver',
          'field' => 'FLUJO_ENTRADA_CALDO_CONCENTRADOR_3',
          'unit' => '',
          'decimals' => 2,
        ],
        'temperatura_interna' => [
          'label' => 'Temp. Interna',
          'source' => 'sqlserver',
          'field' => 'TEMPERATURA_INTERNA_CONCENTRADOR_3',
          'unit' => 'C',
          'decimals' => 2,
        ],
      ],
    ],
    'concentrador_4' => [
      'nombre' => 'Concentrador 4',
      'tipo' => 'Conc4',
      'flujo_field' => 'FLUJO_CONCENTRADOR_5',
      'metric_fields' => [
        'vacio' => 'VACIO_CONCENTRADOR_4',
      ],
      'metricas_extra' => [
        'corriente_concentrador' => [
          'label' => 'Corriente',
          'source' => 'sqlserver',
          'field' => 'CORRIENTE_CONCENTRADOR_4',
          'unit' => 'A',
          'decimals' => 2,
        ],
        'frecuencia_moyno' => [
          'label' => 'Frec. Moyno',
          'source' => 'sqlserver',
          'field' => 'FRECUENCIA_MOYNO_CONCENTRADOR_4',
          'unit' => 'Hz',
          'decimals' => 2,
        ],
        'corriente_moyno' => [
          'label' => 'Corr. Moyno',
          'source' => 'sqlserver',
          'field' => 'CORRIENTE_MOYNO_CONCENTRADOR_4',
          'unit' => 'A',
          'decimals' => 2,
        ],
        'presion_vapor' => [
          'label' => 'Presión Vapor',
          'source' => 'sqlserver',
          'field' => 'PRESION_VAPOR_CONCENTRAADOR_4',
          'unit' => '',
          'decimals' => 2,
        ],
        'setpoint_presion_vapor' => [
          'label' => 'SP Pres. Vapor',
          'source' => 'sqlserver',
          'field' => 'SETPOINT_PRESION_VAPOR_CONCENTRADOR_4',
          'unit' => '',
          'decimals' => 2,
        ],
        'apertura_valvula_vapor' => [
          'label' => 'Apert. Válvula',
          'source' => 'sqlserver',
          'field' => 'APERTURA_VALVULA_VAPOR_CONCENTRADOR_4',
          'unit' => '%',
          'decimals' => 2,
        ],
        'flujo_entrada_caldo' => [
          'label' => 'Flujo Caldo',
          'source' => 'sqlserver',
          'field' => 'FLUJO_ENTRADA_CALDO_CONCENTRADOR_4',
          'unit' => '',
          'decimals' => 2,
        ],
        'temperatura_interna' => [
          'label' => 'Temp. Interna',
          'source' => 'sqlserver',
          'field' => 'TEMPERATURA_INTERNA_CONCENTRADOR_4',
          'unit' => 'C',
          'decimals' => 2,
        ],
        'nivel_tanque_condensados' => [
          'label' => 'Nivel Cond.',
          'source' => 'sqlserver',
          'field' => 'NIVEL_TANQUE_CONDENSADOS_CONCENTRADOR_4',
          'unit' => '%',
          'decimals' => 2,
        ],
      ],
    ],
    'invertido' => [
      'nombre' => 'Invertido',
      'tipo' => 'Invertido',
      'flujo_field' => '',
      'usar_metricas_base' => false,
      'metricas_extra' => [
        'flujo_entrada_evaporador' => [
          'label' => 'Flujo Entrada',
          'source' => 'sqlserver',
          'field' => 'FLUJO_ENTRADA_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'flujo_etapa_1_2' => [
          'label' => 'Flujo E1-E2',
          'source' => 'sqlserver',
          'field' => 'FLUJO_ETAPA_1_A_2_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'flujo_etapa_2_3' => [
          'label' => 'Flujo E2-E3',
          'source' => 'sqlserver',
          'field' => 'FLUJO_ETAPA_2_A_3_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'flujo_salida_evaporador' => [
          'label' => 'Flujo Salida',
          'source' => 'sqlserver',
          'field' => 'FLUJO_SALIDA_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'temperatura_precalentamiento' => [
          'label' => 'Temp. Precal.',
          'source' => 'sqlserver',
          'field' => 'TEMPERATURA_PRECALENTAMIENTO_CALDO_EVAPORADOR_INVERTIDO',
          'unit' => 'C',
          'decimals' => 2,
        ],
        'temperatura_etapa_1' => [
          'label' => 'Temp. E1',
          'source' => 'sqlserver',
          'field' => 'TEMPERATURA_ETAPA_1_EVAPORADOR_INVERTIDO',
          'unit' => 'C',
          'decimals' => 2,
        ],
        'temperatura_salida_agua' => [
          'label' => 'Temp. Agua',
          'source' => 'sqlserver',
          'field' => 'TEMPEATURA_SALIDA_AGUA_ENFRIAMIENTO_EVAPORADOR_INVERTIDO',
          'unit' => 'C',
          'decimals' => 2,
        ],
        'vacio_etapa_1' => [
          'label' => 'Vacío E1',
          'source' => 'sqlserver',
          'field' => 'VACIO_ETAPA_1_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'presion_etapa_1' => [
          'label' => 'Pres. E1',
          'source' => 'sqlserver',
          'field' => 'PRESION_ETAPA_1_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'vacio_etapa_2' => [
          'label' => 'Vacío E2',
          'source' => 'sqlserver',
          'field' => 'VACIO_ETAPA_2_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'presion_etapa_2' => [
          'label' => 'Pres. E2',
          'source' => 'sqlserver',
          'field' => 'PRESION_ETAPA_2_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'vacio_etapa_3' => [
          'label' => 'Vacío E3',
          'source' => 'sqlserver',
          'field' => 'VACIO_ETAPA_3_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'presion_etapa_3' => [
          'label' => 'Pres. E3',
          'source' => 'sqlserver',
          'field' => 'PRESION_ETAPA_3_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'presion_agua_enfriamiento' => [
          'label' => 'Pres. Agua',
          'source' => 'sqlserver',
          'field' => 'PRESION_AGUA_ENFRIAMIENTO_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'nivel_tanque_alimentacion' => [
          'label' => 'Nivel Alim.',
          'source' => 'sqlserver',
          'field' => 'NIVEL_TANQUE_ALIMENTACION_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'presion_vapor' => [
          'label' => 'Pres. Vapor',
          'source' => 'sqlserver',
          'field' => 'PRESION_VAPOR_EVAPORADOR_INVERTIDO',
          'unit' => '',
          'decimals' => 2,
        ],
        'valvula_control_flujo_entrada' => [
          'label' => 'Valv. Flujo',
          'source' => 'sqlserver',
          'field' => 'VALVULA_CONTROL_FLUJO_ENTRADA_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'valvula_control_precalentamiento' => [
          'label' => 'Valv. Precal.',
          'source' => 'sqlserver',
          'field' => 'VALVULA_CONTROL_PRECALENTAMIENTO_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'valvula_control_temperatura_etapa_1' => [
          'label' => 'Valv. Temp. E1',
          'source' => 'sqlserver',
          'field' => 'VALVULA_CONTROL_TEMPERATURA_ETAPA_1_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'valvula_control_nivel_etapa_1' => [
          'label' => 'Valv. Nivel E1',
          'source' => 'sqlserver',
          'field' => 'VALVULA_CONTROL_NIVEL_ETAPA_1_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'moyno_control_nivel_etapa_2' => [
          'label' => 'Moyno Nivel E2',
          'source' => 'sqlserver',
          'field' => 'MOYNO_CONTROL_NIVEL_ETAPA_2_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'moyno_control_nivel_etapa_3' => [
          'label' => 'Moyno Nivel E3',
          'source' => 'sqlserver',
          'field' => 'MOYNO_CONTROL_NIVEL_ETAPA_3_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'valvula_control_presion' => [
          'label' => 'Valv. Presión',
          'source' => 'sqlserver',
          'field' => 'VALVULA_CONTROL_PRESION_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'nivel_etapa_1' => [
          'label' => 'Nivel E1',
          'source' => 'sqlserver',
          'field' => 'NIVEL_ETAPA_1_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'nivel_etapa_2' => [
          'label' => 'Nivel E2',
          'source' => 'sqlserver',
          'field' => 'NIVEL_ETAPA_2_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
        'nivel_etapa_3' => [
          'label' => 'Nivel E3',
          'source' => 'sqlserver',
          'field' => 'NIVEL_ETAPA_3_EVAPORADOR_INVERTIDO',
          'unit' => '%',
          'decimals' => 2,
        ],
      ],
    ],
  ],

  'metricas' => [
    'flujo' => [
      'label' => 'Flujo',
      'unit' => '',
      'source' => 'sqlserver',
      'decimals' => 2,
    ],
    'temperatura' => [
      'label' => 'Temperatura',
      'unit' => 'C',
      'source' => 'mysql_105',
      'decimals' => 2,
      'columns' => ['temperatura'],
    ],
    'vacio' => [
      'label' => 'Vacio',
      'unit' => '',
      'source' => 'mysql_105',
      'decimals' => 2,
      'columns' => ['vacio'],
    ],
    'solidos_entrada' => [
      'label' => 'Solidos Entrada',
      'unit' => '%',
      'source' => 'mysql_105',
      'decimals' => 2,
      'columns' => ['sol_ent'],
    ],
    'solidos_salida' => [
      'label' => 'Solidos Salida',
      'unit' => '%',
      'source' => 'mysql_105',
      'decimals' => 2,
      'columns' => ['sol_sal'],
    ],
  ],

  // Agrega rangos por metrica cuando esten definidos.
  // Ejemplo:
  // 'semaforos' => [
  //   'temperatura' => ['modo' => 'rango', 'verde_min' => 70, 'verde_max' => 75, 'amarillo_min' => 68, 'amarillo_max' => 77],
  // ],
  'semaforos' => [
    'invertido' => [
      'flujo' => [
        'modo' => 'minimo',
        'verde_min' => 60,
        'amarillo_min' => 50,
      ],
    ],
    'vacio' => [
      'modo' => 'minimo',
      'verde_min' => 525,
      'amarillo_min' => 500,
    ],
    'concentrador_1' => [
      'temperatura' => [
        'modo' => 'maximo',
        'verde_max' => 50,
        'amarillo_max' => 55,
      ],
    ],
    'concentrador_2' => [
      'temperatura' => [
        'modo' => 'maximo',
        'verde_max' => 50,
        'amarillo_max' => 55,
      ],
    ],
    'concentrador_3' => [
      'temperatura' => [
        'modo' => 'maximo',
        'verde_max' => 50,
        'amarillo_max' => 55,
      ],
    ],
    'concentrador_4' => [
      'temperatura' => [
        'modo' => 'maximo',
        'verde_max' => 50,
        'amarillo_max' => 55,
      ],
    ],
    'solidos_entrada' => [
      'modo' => 'rango',
      'verde_min' => 21,
      'verde_max' => 22,
      'amarillo_min' => 20,
      'amarillo_max' => 20.999999,
    ],
    'solidos_salida' => [
      'modo' => 'rango',
      'verde_min' => 38,
      'verde_max' => 40,
      'amarillo_min' => 35,
      'amarillo_max' => 37.999999,
    ],
  ],
];
