<?php

$detailConfig = require __DIR__ . '/../secadores-temperatura/config.php';

return array_replace_recursive($detailConfig, [
  'titulo' => 'Secadores',
  'intervalo_actualizacion_ms' => 600000,
  'intervalo_actualizacion_rapida_ms' => 60000,
  'monitoreo_produccion' => [
    'humedad_rangos_tuneles' => ['tunel_1', 'tunel_2'],
    'humedad_rangos_recamaras' => [
      1 => ['verde_lt' => 90, 'amarillo_min' => 90, 'amarillo_max' => 93, 'label' => '< 90 %'],
      2 => ['verde_lt' => 90, 'amarillo_min' => 90, 'amarillo_max' => 93, 'label' => '< 90 %'],
      3 => ['verde_lt' => 90, 'amarillo_min' => 90, 'amarillo_max' => 93, 'label' => '< 90 %'],
      4 => ['verde_lt' => 60, 'amarillo_min' => 60, 'amarillo_max' => 65, 'label' => '< 60 %'],
      5 => ['verde_lt' => 60, 'amarillo_min' => 60, 'amarillo_max' => 65, 'label' => '< 60 %'],
      6 => ['verde_lt' => 49, 'amarillo_min' => 49, 'amarillo_max' => 54, 'label' => '< 49 %'],
      7 => ['verde_lt' => 37, 'amarillo_min' => 37, 'amarillo_max' => 42, 'label' => '< 37 %'],
      8 => ['verde_lt' => 30, 'amarillo_min' => 30, 'amarillo_max' => 35, 'label' => '< 30 %'],
      9 => ['verde_lt' => 30, 'amarillo_min' => 30, 'amarillo_max' => 35, 'label' => '< 30 %'],
    ],
  ],
  'mysql_secadores' => [
    'host' => '192.168.1.105',
    'port' => 3306,
    'dbname' => 'bd_secadores',
    'user' => 'user_pro',
    'pass' => 'Pr0g3l2025PR',
    'charset' => 'utf8mb4',
    'timeout' => 3,
  ],
  'mysql_producto' => [
    'host' => '192.168.1.105',
    'port' => 3306,
    'dbname' => 'progel_procesos',
    'user' => 'user_pro',
    'pass' => 'Pr0g3l2025PR',
    'charset' => 'utf8mb4',
    'timeout' => 3,
    'tabla_datos' => 'datos_producto',
    'columnas_orden' => ['id_datos_hora', 'id'],
  ],
  'mysql_verificacion_secado' => [
    'host' => '192.168.1.105',
    'port' => 3306,
    'dbname' => 'progel_procesos',
    'user' => 'user_pro',
    'pass' => 'Pr0g3l2025PR',
    'charset' => 'utf8mb4',
    'timeout' => 3,
  ],
  'indicadores_superiores' => [
    'viscosidad_churro' => [
      'label' => 'Viscosidad churro',
      'source' => 'mysql_producto',
      'field' => 'churro_viscosidad',
      'unit' => '',
      'available' => true,
      'empty_label' => '-',
      'usar_anterior_si_cero_o_null' => true,
      'semaforo' => [
        'modo' => 'bandas',
        'bandas' => [
          ['max' => 39.999999, 'estado' => 'verde'],
          ['min' => 40, 'max' => 43, 'estado' => 'dorado'],
          ['min' => 43.000001, 'estado' => 'azul'],
        ],
      ],
      'leyenda' => '< 40',
    ],
    'solido_entrada' => [
      'label' => 'Sólido entrada',
      'source' => 'mysql_producto',
      'field' => 'churro_solidos',
      'unit' => '%',
      'available' => true,
      'empty_label' => '-',
      'usar_anterior_si_cero_o_null' => true,
      'semaforo' => [
        'modo' => 'bandas',
        'bandas' => [
          ['max' => 34.999999, 'estado' => 'rojo'],
          ['min' => 35, 'max' => 36.999999, 'estado' => 'amarillo'],
          ['min' => 37, 'estado' => 'verde'],
        ],
      ],
      'leyenda' => '>= 37 %',
    ],
  ],
  'metricas_por_tunel' => [
    'tunel_1' => [
      'velocidad_banda' => [
        'group' => 'Banda',
        'label' => 'Velocidad banda',
        'field' => 'FUNCIONAMIENTO_BANDA_TRANSPORTADORA',
        'unit' => '',
        'available' => true,
        'empty_label' => 'Sin dato',
        'formula' => [
          'tipo' => 'factor',
          'factor' => 18.72 / 60,
        ],
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 14.5,
          'verde_max' => 15,
        ],
        'leyenda' => '14.5-15',
      ],
      'caudal_aire' => [
        'group' => 'Banda',
        'label' => 'Caudal aire',
        'source' => 'mysql_secadores',
        'field' => 'caudal',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'lookup' => [
          'table' => 'secadores_caudal_registros',
          'key_column' => 'tunel_key',
          'key_value' => 'tunel_1',
          'timestamp_column' => 'fecha_hora',
          'date_filter' => false,
        ],
        'semaforo' => [
          'modo' => 'minimo',
          'verde_min' => 90000,
          'amarillo_min' => 89000,
        ],
        'leyenda' => 'Verde >= 90,000 m³/h | Atención >= 89,000 | Crítico <89,000',
      ],
      'agua_caliente_suministro' => [
        'group' => 'Agua y vapor',
        'label' => 'Agua suministro',
        'field' => 'TEMPERATURA_ENTRADA_AGUA_CALIENTE',
        'unit' => '°C',
        'available' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 88,
          'verde_max' => 92,
          'amarillo_min' => 85,
          'amarillo_max' => 87.99,
        ],
        'leyenda' => 'Ideal 90 °C | Verde 88-92 | Atención 85-87 | Crítico <85',
      ],
      'agua_caliente_retorno' => [
        'group' => 'Agua y vapor',
        'label' => 'Agua retorno',
        'field' => 'TEMPERATURA_RETORNO_AGUA_CALIENTE',
        'unit' => '°C',
        'available' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 68,
          'verde_max' => 72,
        ],
        'leyenda' => 'Ideal 70 °C | Verde 68-72',
      ],
      'presion_vapor' => [
        'group' => 'Agua y vapor',
        'label' => 'Presión vapor',
        'field' => 'PRESION_DE_VAPOR',
        'unit' => 'bar(a)',
        'available' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 3.0,
          'verde_max' => 3.2,
          'amarillo_min' => 2.8,
          'amarillo_max' => 2.99,
        ],
        'leyenda' => 'Ideal 3.1 bar(a) | Verde 3.0-3.2 | Atención 2.8-2.9 | Crítico <2.8',
      ],
      'humedad_zona_1_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 1',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_1_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_2_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 2',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_2_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_3_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 3',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_3_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_4_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 4',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_4_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_5_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 5',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_5_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_6_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 6',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_6_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_7_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 7',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_7_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_8_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 8',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_8_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_zona_9_inferior' => [
        'group' => 'Humedades',
        'label' => 'REC 9',
        'field' => 'SECADOR_AS_HUMEDAD_ZONA_9_INFERIOR',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'verificacion_altura_galleta' => [
        'group' => 'Verificación de secado',
        'label' => 'Altura galleta',
        'source' => 'mysql_verificacion_secado',
        'field' => 'altura_galleta',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 6.5,
          'verde_max' => 7.5,
          'amarillo_min' => 6.0,
          'amarillo_max' => 6.5,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_flujo' => [
        'group' => 'Verificación de secado',
        'label' => 'Flujo',
        'source' => 'mysql_verificacion_secado',
        'field' => 'flujo',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 26,
          'verde_max' => 28,
          'amarillo_min' => 24,
          'amarillo_max' => 26,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hz' => [
        'group' => 'Verificación de secado',
        'label' => 'Hz',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hz',
        'unit' => 'Hz',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 45,
          'verde_max' => 52,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hum_penultima' => [
        'group' => 'Verificación de secado',
        'label' => 'Hum. penúltima',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hum_penultima',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 12,
          'amarillo_max' => 15,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hum_ultima' => [
        'group' => 'Verificación de secado',
        'label' => 'Hum. última',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hum_ultima',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 12,
          'amarillo_max' => 15,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_rc9' => [
        'group' => 'Verificación de secado',
        'label' => 'RC9',
        'source' => 'mysql_verificacion_secado',
        'field' => 'rc9',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 10,
          'amarillo_max' => 12,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hum_relativa_cam5' => [
        'group' => 'Verificación de secado',
        'label' => 'Hum. rel. cam5',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hum_relativa_cam5',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 36,
          'amarillo_max' => 37,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_textura' => [
        'group' => 'Verificación de secado',
        'label' => 'Textura',
        'source' => 'mysql_verificacion_secado',
        'field' => 'textura',
        'tipo' => 'texto',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'texto',
          'verde' => ['Firme'],
          'amarillo' => ['Plástica'],
          'rojo' => ['Húmeda'],
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '1',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
    ],
    'tunel_2' => [
      'velocidad_banda' => [
        'group' => 'Banda',
        'label' => 'Velocidad banda',
        'field' => 'T5VELB',
        'unit' => '',
        'available' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 14.5,
          'verde_max' => 15,
        ],
        'leyenda' => '14.5-15',
      ],
      'caudal_aire' => [
        'group' => 'Banda',
        'label' => 'Caudal aire',
        'source' => 'mysql_secadores',
        'field' => 'caudal',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'lookup' => [
          'table' => 'secadores_caudal_registros',
          'key_column' => 'tunel_key',
          'key_value' => 'tunel_2',
          'timestamp_column' => 'fecha_hora',
          'date_filter' => false,
        ],
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 74000,
          'verde_max' => 82500,
          'amarillo_min' => 70000,
          'amarillo_max' => 83999.99,
        ],
        'leyenda' => 'Ideal 75,000 m³/h | Verde 74,000-82,500 | Atención 70,000-73,999 | Crítico <70,000 o >82,500',
      ],
      'agua_caliente_suministro' => [
        'group' => 'Agua y vapor',
        'label' => 'Agua suministro',
        'field' => 'ENTRADA_DE_AGUA_CALIENTE_DE_TUNEL_1',
        'unit' => '°C',
        'available' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 88,
          'verde_max' => 92,
          'amarillo_min' => 85,
          'amarillo_max' => 87.99,
        ],
        'leyenda' => 'Ideal 90 °C | Verde 88-92 | Atención 85-87 | Crítico <85',
      ],
      'agua_caliente_retorno' => [
        'group' => 'Agua y vapor',
        'label' => 'Agua retorno',
        'field' => 'RETORNO_DE_AGUA_CALIENTE_DE_TUNEL_1',
        'unit' => '°C',
        'available' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 68,
          'verde_max' => 72,
        ],
        'leyenda' => 'Ideal 70 °C | Verde 68-72',
      ],
      'presion_vapor' => [
        'group' => 'Agua y vapor',
        'label' => 'Presión vapor',
        'field' => 'PRESION_DE_VAPOR',
        'unit' => 'bar(a)',
        'available' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 3.0,
          'verde_max' => 3.2,
          'amarillo_min' => 2.8,
          'amarillo_max' => 2.99,
        ],
        'leyenda' => 'Ideal 3.1 bar(a) | Verde 3.0-3.2 | Atención 2.8-2.9 | Crítico <2.8',
      ],
      'humedad_recamara_1' => [
        'group' => 'Humedades',
        'label' => 'REC 1',
        'field' => '',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'leyenda' => 'Rango pendiente de definir',
      ],
      'humedad_recamara_2' => [
        'group' => 'Humedades',
        'label' => 'REC 2',
        'field' => 'T5SHZ2PV',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_recamara_3' => [
        'group' => 'Humedades',
        'label' => 'REC 3',
        'field' => '',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'leyenda' => 'Rango pendiente de definir',
      ],
      'humedad_recamara_4' => [
        'group' => 'Humedades',
        'label' => 'REC 4',
        'field' => 'T5SHZ4PV',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_recamara_5' => [
        'group' => 'Humedades',
        'label' => 'REC 5',
        'field' => '',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'leyenda' => 'Rango pendiente de definir',
      ],
      'humedad_recamara_6' => [
        'group' => 'Humedades',
        'label' => 'REC 6',
        'field' => '',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'leyenda' => 'Rango pendiente de definir',
      ],
      'humedad_recamara_7' => [
        'group' => 'Humedades',
        'label' => 'REC 7',
        'field' => '',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'leyenda' => 'Rango pendiente de definir',
      ],
      'humedad_recamara_8' => [
        'group' => 'Humedades',
        'label' => 'Rec 8',
        'field' => 'T5SHZ8PV',
        'unit' => '%',
        'available' => true,
        'empty_label' => 'Sin dato',
        'leyenda' => 'Lectura actual | Rango pendiente de definir',
      ],
      'humedad_recamara_9' => [
        'group' => 'Humedades',
        'label' => 'REC 9',
        'field' => '',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'leyenda' => 'Rango pendiente de definir',
      ],
      'humedad_suministro_aire' => [
        'group' => 'Humedades',
        'label' => 'Aire suministro',
        'field' => 'T5HHVACZ1PV',
        'unit' => 'g/kg',
        'available' => true,
        'hidden' => true,
        'empty_label' => 'Sin dato',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 7.5,
          'amarillo_max' => 8.5,
        ],
        'leyenda' => 'Ideal ≤ 7.5 g/kg | Verde ≤ 7.5 | Atención 7.6-8.5 | Crítico > 8.5',
      ],
      'verificacion_altura_galleta' => [
        'group' => 'Verificación de secado',
        'label' => 'Altura galleta',
        'source' => 'mysql_verificacion_secado',
        'field' => 'altura_galleta',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 6.5,
          'verde_max' => 7.5,
          'amarillo_min' => 6.0,
          'amarillo_max' => 6.5,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_flujo' => [
        'group' => 'Verificación de secado',
        'label' => 'Flujo',
        'source' => 'mysql_verificacion_secado',
        'field' => 'flujo',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'minimo',
          'verde_min' => 24,
          'amarillo_min' => 22,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hz' => [
        'group' => 'Verificación de secado',
        'label' => 'Hz',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hz',
        'unit' => 'Hz',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'minimo',
          'verde_min' => 52.8,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hum_penultima' => [
        'group' => 'Verificación de secado',
        'label' => 'Hum. penúltima',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hum_penultima',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 12,
          'amarillo_max' => 15,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hum_ultima' => [
        'group' => 'Verificación de secado',
        'label' => 'Hum. última',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hum_ultima',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 12,
          'amarillo_max' => 15,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_rc9' => [
        'group' => 'Verificación de secado',
        'label' => 'REC 9',
        'source' => 'mysql_verificacion_secado',
        'field' => 'rc9',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 10,
          'amarillo_max' => 12,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_hum_relativa_cam5' => [
        'group' => 'Verificación de secado',
        'label' => 'Hum. rel. rec 5',
        'source' => 'mysql_verificacion_secado',
        'field' => 'hum_relativa_cam5',
        'unit' => '%',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 36,
          'amarillo_max' => 37,
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
      'verificacion_textura' => [
        'group' => 'Verificación de secado',
        'label' => 'Textura',
        'source' => 'mysql_verificacion_secado',
        'field' => 'textura',
        'tipo' => 'texto',
        'unit' => '',
        'available' => true,
        'empty_label' => '-',
        'semaforo' => [
          'modo' => 'texto',
          'verde' => ['Firme'],
          'amarillo' => ['Plástica'],
          'rojo' => ['Húmeda'],
        ],
        'lookup' => [
          'table' => 'verificacion_secado',
          'key_column' => 'secador',
          'key_value' => '2',
          'timestamp_column' => 'creado_en',
          'date_filter' => false,
          'order_columns' => ['creado_en', 'id'],
        ],
      ],
    ],
  ],
  'votators_por_tunel' => [
    'tunel_1' => [
      'votator_1' => [
        'label' => 'Votator 1',
        'campos' => [
          'flujo' => [
            'label' => 'Flujo',
            'source' => 'sqlserver',
            'field' => 'FLUJO_VOTATOR_1_SA',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'bandas',
              'bandas' => [
                ['max' => 10, 'estado' => 'rojo'],
                ['min' => 10.5, 'max' => 11.499999, 'estado' => 'amarillo'],
                ['min' => 11.5, 'max' => 12.5, 'estado' => 'verde'],
                ['min' => 12.500001, 'max' => 13, 'estado' => 'amarillo'],
                ['min' => 13, 'estado' => 'rojo'],
              ],
            ],
            'leyenda' => '11.5-12.5',
          ],
          'presion_cuajado' => [
            'label' => 'Presión cuajado',
            'source' => 'sqlserver',
            'field' => 'PRESION_CUAJADO_VOTATOR_1',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'rango',
              'verde_min' => 24,
              'verde_max' => 26,
              'amarillo_min' => 23,
              'amarillo_max' => 27,
            ],
            'leyenda' => '24-26 kg/cm2',
          ],
        ],
      ],
      'votator_2' => [
        'label' => 'Votator 2',
        'campos' => [
          'flujo' => [
            'label' => 'Flujo',
            'source' => 'sqlserver',
            'field' => 'FLUJO_VOTATOR_2_SA',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'bandas',
              'bandas' => [
                ['max' => 10, 'estado' => 'rojo'],
                ['min' => 10.5, 'max' => 11.499999, 'estado' => 'amarillo'],
                ['min' => 11.5, 'max' => 12.5, 'estado' => 'verde'],
                ['min' => 12.500001, 'max' => 13, 'estado' => 'amarillo'],
                ['min' => 13, 'estado' => 'rojo'],
              ],
            ],
            'leyenda' => '11.5-12.5',
          ],
          'presion_cuajado' => [
            'label' => 'Presión cuajado',
            'source' => 'sqlserver',
            'field' => 'PRESION_CUAJADO_VOTATOR_2_SA',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'rango',
              'verde_min' => 24,
              'verde_max' => 26,
              'amarillo_min' => 23,
              'amarillo_max' => 27,
            ],
            'leyenda' => '24-26 kg/cm2',
          ],
        ],
      ],
    ],
    'tunel_2' => [
      'votator_3' => [
        'label' => 'Votator 3',
        'campos' => [
          'flujo' => [
            'label' => 'Flujo',
            'source' => 'sqlserver',
            'field' => 'FLUJO_VOTATOR_1',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'bandas',
              'bandas' => [
                ['max' => 10, 'estado' => 'rojo'],
                ['min' => 10.5, 'max' => 11.499999, 'estado' => 'amarillo'],
                ['min' => 11.5, 'max' => 12.5, 'estado' => 'verde'],
                ['min' => 12.500001, 'max' => 13, 'estado' => 'amarillo'],
                ['min' => 13, 'estado' => 'rojo'],
              ],
            ],
            'leyenda' => '11.5-12.5',
          ],
          'presion_cuajado' => [
            'label' => 'Presión cuajado',
            'source' => 'sqlserver',
            'field' => 'PRESION__CUAJADO_VOTATOR_3',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'rango',
              'verde_min' => 24,
              'verde_max' => 26,
              'amarillo_min' => 23,
              'amarillo_max' => 27,
            ],
            'leyenda' => '24-26 kg/cm2',
          ],
        ],
      ],
      'votator_4' => [
        'label' => 'Votator 4',
        'campos' => [
          'flujo' => [
            'label' => 'Flujo',
            'source' => 'sqlserver',
            'field' => 'FLUJO_VOTATOR_2',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'bandas',
              'bandas' => [
                ['max' => 10, 'estado' => 'rojo'],
                ['min' => 10.5, 'max' => 11.499999, 'estado' => 'amarillo'],
                ['min' => 11.5, 'max' => 12.5, 'estado' => 'verde'],
                ['min' => 12.500001, 'max' => 13, 'estado' => 'amarillo'],
                ['min' => 13, 'estado' => 'rojo'],
              ],
            ],
            'leyenda' => '11.5-12.5',
          ],
          'presion_cuajado' => [
            'label' => 'Presión cuajado',
            'source' => 'sqlserver',
            'field' => 'PRESION__CUAJADO_VOTATOR_4',
            'unit' => '',
            'available' => true,
            'empty_label' => 'Sin dato',
            'semaforo' => [
              'modo' => 'rango',
              'verde_min' => 24,
              'verde_max' => 26,
              'amarillo_min' => 23,
              'amarillo_max' => 27,
            ],
            'leyenda' => '24-26 kg/cm2',
          ],
        ],
      ],
    ],
  ],
]);
