<?php

declare(strict_types=1);

$productionSourceConfig = require __DIR__ . '/../avance-produccion-hora/config.php';

return [
  'titulo' => 'Reporte de Energía',
  'subtitulo' => 'Recibos, consumo y eficiencia energética por año',
  'actualizado' => 'Sin captura',
  'timezone' => 'America/Mexico_City',
  'database_key' => 'prod',
  'production_database' => (array)($productionSourceConfig['database'] ?? []),
  'hora_corte' => '07:00:00',
  'gas_natural_invoice_api' => [
    'company' => 'Progel',
    'url' => 'http://192.168.1.104:5000/api/facturas-compra',
    'provider' => 179,
    'xml_root_env' => 'ENERGIA_GAS_XML_ROOT',
    'xml_root' => '/mnt/empresas',
    'company_paths' => ['PRUEBAS', 'PRUEBA'],
    'invoice_month_offset' => 0,
    'years' => [2025, 2026],
    'calorific_value_mj_m3' => 38,
    'timeout' => 25,
    'cache_ttl' => 3600,
    'cache_version' => 4,
  ],
  'water_invoice_api' => [
    'company' => 'Progel',
    'url' => 'http://192.168.1.104:5000/api/facturas-compra',
    'provider' => 900,
    'timeout' => 20,
    'cache_ttl' => 3600,
    'cache_version' => 1,
  ],
  'electricity_cost_apis' => [
    [
      'company' => 'Progel',
      'url' => 'http://192.168.1.104:5000/api/facturas-compra',
      'provider' => 2249,
      'detail_segment' => 'MAT',
      'payment_month_offset' => -1,
      'minimum_invoice_amount' => 100000,
      'timeout' => 20,
      'cache_ttl' => 3600,
      'cache_version' => 4,
    ],
    [
      'company' => 'AMINOVUS',
      'url' => 'http://192.168.1.104:5000/api/facturas-compra',
      'provider' => 49,
      'query' => ['empresa' => 'aminovus'],
      'detail_segment' => 'MAT',
      'payment_month_offset' => -1,
      'minimum_invoice_amount' => 100000,
      'timeout' => 20,
      'cache_ttl' => 3600,
      'cache_version' => 1,
    ],
    [
      'company' => 'NOVA',
      'url' => 'http://192.168.1.104:5000/api/facturas-compra',
      'provider' => 189,
      'query' => ['empresa' => 'nova'],
      'detail_segment' => 'MAT',
      'payment_month_offset' => -1,
      'minimum_invoice_amount' => 0,
      'timeout' => 20,
      'cache_ttl' => 3600,
      'cache_version' => 2,
    ],
  ],
  'acceso_agua' => [
    'password_hash_env' => 'ENERGIA_AGUA_CLAVE_HASH',
    'timeout_seconds' => 2400,
  ],
  'consumos' => [
    'electricidad' => [
      'label' => 'Energía eléctrica',
      'description' => 'Por kg de grenetina producida',
      'unit' => 'kWh/kg',
      'total_unit' => 'kWh',
      'color' => '#475569',
      'value' => null,
      'icon' => 'fa-bolt',
    ],
    'gas_natural' => [
      'label' => 'Gas natural',
      'description' => 'Por kg de grenetina producida',
      'unit' => 'm³/kg',
      'total_unit' => 'm³',
      'color' => '#78716c',
      'value' => null,
      'icon' => 'fa-fire-flame-simple',
    ],
    'agua' => [
      'label' => 'Agua',
      'description' => 'Por kg de grenetina producida',
      'unit' => 'm³/kg',
      'total_unit' => 'm³',
      'color' => '#2563eb',
      'value' => null,
      'icon' => 'fa-droplet',
    ],
  ],
  'recuperaciones' => [
    'recuperacion_grasa' => [
      'label' => 'Recuperación de grasa',
      'm3' => null,
      'valor' => null,
      'icon' => 'fa-oil-can',
      'unit' => 'm³',
      'ratio_unit' => 'm³/kg',
      'color' => '#64748b',
    ],
    'ollas' => [
      'label' => 'Ollas',
      'm3' => null,
      'valor' => null,
      'icon' => 'fa-fire-burner',
      'unit' => 'm³',
      'ratio_unit' => 'm³/kg',
      'color' => '#a16207',
    ],
    'polimeros' => [
      'label' => 'Polímeros',
      'm3' => null,
      'valor' => null,
      'icon' => 'fa-flask',
      'unit' => 'm³',
      'ratio_unit' => 'm³/kg',
      'color' => '#6b7280',
    ],
  ],
  'generacion' => [
    'panel_solar' => [
      'label' => 'Producción panel solar',
      'kw' => null,
      'valor' => null,
      'icon' => 'fa-solar-panel',
      'unit' => 'kW',
      'ratio_unit' => 'kW/kg',
      'color' => '#15803d',
    ],
    'cogenerador' => [
      'label' => 'Producción cogenerador',
      'kw' => null,
      'valor' => null,
      'icon' => 'fa-industry',
      'unit' => 'kW',
      'ratio_unit' => 'kW/kg',
      'color' => '#0f766e',
    ],
  ],
];
