<?php
define('IP', '192.168.1.105');
$groups = [
  'compras' => [
    'title' => 'Compras',
    'description' => 'Consumo, costos y seguimiento de insumos y refacciones.',
    'icon' => 'fa-cart-shopping',
    'color' => '#0f766e',
  ],
  'ventas' => [
    'title' => 'Ventas',
    'description' => 'Indicadores de ventas, clientes y seguimiento de ventas.',
    'icon' => 'fa-store',
    'color' => '#2563eb',
  ],
  'produccion' => [
    'title' => 'Producción',
    'description' => 'Monitoreo operativo de procesos, equipos y condiciones en planta.',
    'icon' => 'fa-gauge-high',
    'color' => '#7c3aed',
  ],
  'RRHH' => [
    'title' => 'RRHH',
    'description' => 'Asistencia, checadas y seguimiento del personal administrativo.',
    'icon' => 'fa-users',
    'color' => '#db2777',
  ],
  'ingenieria' => [
    'title' => 'Ingeniería | Mtto',
    'description' => 'Seguimiento de proyectos, hitos y compromisos directivos.',
    'icon' => 'fa-cogs',
    'color' => '#ea580c',
  ],
  'direccion' => [
    'title' => 'Dirección',
    'description' => 'Indicadores clave para seguimiento de resultados y toma de decisiones estratégicas.',
    'icon' => 'fa-briefcase',
    'color' => '#047857',
  ],
  'direccion-adjunta' => [
    'title' => 'Muro',
    'description' => 'Tablero para dirección adjunta.',
    'icon' => 'fa-table-cells-large',
    'color' => '#7c2d12',
    'visible_modes' => ['muro'],
  ],
  'direccion-general' => [
    'title' => 'Dirección General',
    'description' => 'Tablero ejecutivo para dirección general.',
    'icon' => 'fa-building-columns',
    'color' => '#0f766e',
    'visible_modes' => ['direccion-general'],
  ],
];

return [
  'groups' => $groups,
  'reports' => [
    [
      'slug' => 'quimicos-produccion',
      'title' => 'QUÍMICOS / Producción',
      'description' => 'Consumo semanal de químicos vs kilos producidos, con semáforos, comparativa anual, tabla y gráfico.',
      'icon' => 'fa-chart-line',
      'color' => '#10b981',
      'groups' => ['compras'],
      'url' => './quimicos-produccion/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'empaques-produccion',
      'title' => 'EMPAQUES / Producción',
      'description' => 'Consumo semanal de empaques vs kilos producidos, con semáforos, comparativa anual, tabla y gráfico.',
      'icon' => 'fa-chart-line',
      'color' => '#10b981',
      'groups' => ['compras'],
      'url' => './empaques-produccion/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'refacciones-criticas',
      'title' => 'REFACCIONES CRÍTICAS',
      'description' => 'Consumo semanal de refacciones críticas con semáforos, comparativa anual y desglose por refacción.',
      'icon' => 'fa-wrench',
      'color' => '#10b981',
      'groups' => ['compras'],
      'url' => './refacciones-criticas/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'refacciones-generales',
      'title' => 'REFACCIONES GENERALES',
      'description' => 'Consumo semanal de refacciones generales con semáforos, comparativa anual y desglose por refacción.',
      'icon' => 'fa-toolbox',
      'color' => '#10b981',
      'groups' => ['compras'],
      'url' => './refacciones-generales/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'ventas-por-cliente',
      'title' => 'VENTAS / Por Cliente',
      'description' => 'Análisis de ventas y comportamiento de compra por cliente, con semáforos comparativos año anterior vs actual. Clasificación industrial/comercial.',
      'icon' => 'fa-cart-shopping',
      'color' => '#10b981',
      'groups' => ['ventas'],
      'url' => './ventas-por-cliente/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'avance-produccion',
      'title' => 'Avance de Producción',
      'description' => 'Avance mensual de toneladas, rendimiento, finos y déficit contra objetivo diario.',
      'icon' => 'fa-gauge-high',
      'color' => '#10b981',
      'groups' => ['produccion', 'direccion-general'],
      'url' => './avance-produccion/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'materia-prima',
      'title' => 'Materia Prima',
      'description' => 'Consumo de materia prima, rendimiento general y rendimiento por proveedor con agrupación por tipo de material.',
      'icon' => 'fa-boxes-stacked',
      'color' => '#10b981',
      'groups' => ['produccion', 'direccion-general'],
      'url' => './materia-prima/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'secadores',
      'title' => 'SECADORES',
      'description' => 'Monitoreo del comportamiento de los secadores con semáforos configurables por variable y actualización automática.',
      'icon' => 'fa-fan',
      'color' => '#10b981',
      'groups' => ['produccion', 'direccion-general'],
      'url' => './secadores/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'secadores-temperaturas',
      'title' => 'SECADORES / Temperaturas',
      'description' => 'Monitoreo histórico en tiempo casi real de temperaturas por túnel, con semáforos configurables por variable y actualización automática.',
      'icon' => 'fa-fan',
      'color' => '#10b981',
      'groups' => ['produccion'],
      'url' => './secadores-temperatura/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'calidad-produccion',
      'title' => 'CALIDAD / Producción',
      'description' => 'Distribución de calidad por día, semana o mes con topes por color, pastel por kilos y comportamiento por periodo.',
      'icon' => 'fa-vial-circle-check',
      'color' => '#10b981',
      'groups' => ['produccion', 'direccion-general'],
      'url' => './calidad-produccion/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'secadores-caudal',
      'title' => 'SECADORES / Caudal',
      'description' => 'Monitoreo histórico en tiempo casi real del caudal de aire por túnel, con semáforos configurables por variable y actualización automática.',
      'icon' => 'fa-fan',
      'color' => '#10b981',
      'groups' => ['produccion'],
      'url' => 'http://' . IP . '/reportes_produccion/reports/secadores-caudal/index.php',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'bitacora-procesos',
      'title' => 'BITÁCORA / Procesos',
      'description' => 'Registro histórico de procesos con seguimiento en tiempo real.',
      'icon' => 'fa-clipboard-list',
      'color' => '#10b981',
      'groups' => ['produccion'],
      'url' => 'http://' . IP . '/progel_Bitacora/dashboard_gerencia.php',
      'external' => true,
      'enabled' => true,
    ],
    /* [
      'slug' => 'grasa',
      'title' => 'Control de Grasa',
      'description' => 'Monitoreo del consumo de grasa. ',
      'icon' => 'fa-oil-can',
      'color' => '#10b981',
      'groups' => ['produccion'],
      'url' => 'http://' . IP . '/reportes_produccion/reports/secadores-caudal/index.php',
      'external' => true,
      'enabled' => true,
    ], */
    [
      'slug' => 'biotime-administrativos',
      'title' => 'BIOTIME / Administrativos',
      'description' => 'Semáforo de asistencia administrativa desde BioTime con resumen por empleado y detalle diario de incidencias.',
      'icon' => 'fa-id-badge',
      'color' => '#10b981',
      'groups' => ['RRHH'],
      'url' => './biotime-administrativos/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'proyectos',
      'title' => 'PROYECTOS',
      'description' => 'Vista de proyectos por milestone con porcentaje de avance, responsable, filtros de estatus y detalle por tareas.',
      'icon' => 'fa-diagram-project',
      'color' => '#10b981',
      'groups' => ['ingenieria', 'direccion-adjunta', 'direccion-general'],
      'url' => './proyectos/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'growatt',
      'title' => 'Panel Solar / Growatt',
      'description' => 'Vista de proyectos por milestone con porcentaje de avance, responsable, filtros de estatus y detalle por tareas.',
      'icon' => 'fa-solar-panel',
      'color' => '#10b981',
      'groups' => ['ingenieria'],
      'url' => 'https://server.growatt.com/login',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'programa-mantenimiento',
      'title' => 'Programa de Mantenimiento',
      'description' => 'Seguimiento y gestión del programa de mantenimiento preventivo y correctivo.',
      'icon' => 'fa-wrench',
      'color' => '#10b981',
      'groups' => ['ingenieria'],
      'url' => 'http://' . IP . '/control_calderas/Mantenimiento_Preventivo/programa_anual.php',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'calderas',
      'title' => 'Calderas',
      'description' => 'Seguimiento y gestión del programa de mantenimiento preventivo y correctivo.',
      'icon' => 'fa-fire',
      'color' => '#10b981',
      'groups' => ['ingenieria'],
      'url' => 'http://' . IP . '/control_calderas/control_calderas/reporte.php',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'hikvision-administrativos',
      'title' => 'HIKVISION / Administrativos',
      'description' => 'Semáforo de asistencia administrativa desde Hikvision con eventos de acceso válidos, resumen por empleado y detalle diario.',
      'icon' => 'fa-camera',
      'color' => '#10b981',
      'groups' => ['RRHH'],
      'url' => './hikvision-administrativos/index.php',
      'enabled' => true,
    ],
    [
      'slug' => 'hoshin-kanri',
      'title' => 'HOSHIN KANRI',
      'description' => 'Seguimiento de objetivos y metas estratégicas mediante el methodology Hoshin Kanri.',
      'icon' => 'fa-chart-bar',
      'color' => '#10b981',
      'groups' => ['RRHH', 'direccion-adjunta'],
      'url' => 'http://' . IP . '/hoshin_kanri/index.php',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'sai',
      'title' => 'SAI',
      'description' => 'Sistema de ERP.',
      'icon' => 'fa-database',
      'color' => '#10b981',
      'groups' => ['direccion-adjunta'],
      'url' => 'http://192.168.1.104/alphaerpweb/',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'sistema-produccion',
      'title' => 'Sistema Producción',
      'description' => 'Sistema de producción para seguimiento de órdenes, procesos y resultados en planta.',
      'icon' => 'fa-industry',
      'color' => '#10b981',
      'groups' => ['direccion-adjunta'],
      'url' => 'http://' . IP . '/sis_preparacion/revolturas',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'benchmark-competencia',
      'title' => 'Benchmark de Competencia',
      'description' => 'Análisis de desempeño en comparación con la competencia.',
      'icon' => 'fa-chart-bar',
      'color' => '#10b981',
      'groups' => ['direccion-adjunta', 'ventas', 'direccion-general'],
      'url' => './benchmark-competencia/index.php',
      'external' => true,
      'enabled' => true,
    ],
    [
      'slug' => 'kpis-direccion',
      'title' => 'KPIs / Dirección',
      'description' => 'Indicadores clave para seguimiento de resultados y toma de decisiones estratégicas.',
      'icon' => 'fa-chart-line',
      'color' => '#047857',
      'groups' => ['direccion'],
      'url' => './kpis-direccion/index.php',
      'enabled' => false,
    ],

    // Ejemplo futuro:
    // [
    //   'slug' => 'inventario-rotacion',
    //   'title' => 'Inventario / Rotación',
    //   'description' => 'Rotación de inventario por periodo.',
    //   'icon' => 'fa-boxes-stacked',
    //   'color' => '#3b82f6',
    //   'groups' => ['compras', 'produccion'],
    //   'url' => './inventario-rotacion/index.php',
    //   'enabled' => false,
    // ],
  ],
];
