<?php

return [
  [
    'slug' => 'quimicos-produccion',
    'title' => 'QUÍMICOS / Producción',
    'description' => 'Consumo semanal de químicos vs kilos producidos, con semáforos, comparativa anual, tabla y gráfico.',
    'icon' => 'fa-chart-line',
    'color' => '#10b981',
    'url' => './quimicos-produccion/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'empaques-produccion',
    'title' => 'EMPAQUES / Producción',
    'description' => 'Consumo semanal de empaques vs kilos producidos, con semáforos, comparativa anual, tabla y gráfico.',
    'icon' => 'fa-chart-line',
    'color' => '#10b981',
    'url' => './empaques-produccion/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'refacciones-criticas',
    'title' => 'REFACCIONES CRÍTICAS',
    'description' => 'Consumo semanal de refacciones críticas con semáforos, comparativa anual y desglose por refacción.',
    'icon' => 'fa-wrench',
    'color' => '#10b981',
    'url' => './refacciones-criticas/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'refacciones-generales',
    'title' => 'REFACCIONES GENERALES',
    'description' => 'Consumo semanal de refacciones generales con semáforos, comparativa anual y desglose por refacción.',
    'icon' => 'fa-toolbox',
    'color' => '#10b981',
    'url' => './refacciones-generales/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'ventas-por-cliente',
    'title' => 'VENTAS / Por Cliente',
    'description' => 'Análisis de ventas y comportamiento de compra por cliente, con semáforos comparativos año anterior vs actual. Clasificación industrial/comercial.',
    'icon' => 'fa-cart-shopping',
    'color' => '#f59e0b',
    'url' => './ventas-por-cliente/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'secadores',
    'title' => 'SECADORES',
    'description' => 'Tablero resumen de secadores con vista ejecutiva de ambos túneles, temperaturas por zona y semáforos operativos.',
    'icon' => 'fa-fan',
    'color' => '#0f766e',
    'url' => './secadores/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'secadores-temperatura',
    'title' => 'SECADORES / Temperatura Detalle',
    'description' => 'Detalle histórico de temperaturas por túnel, con semáforos configurables por variable y actualización automática.',
    'icon' => 'fa-fan',
    'color' => '#0f766e',
    'url' => './secadores-temperatura/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'biotime-administrativos',
    'title' => 'BIOTIME / Administrativos',
    'description' => 'Semáforo de asistencia administrativa desde BioTime con resumen por empleado y detalle diario de incidencias.',
    'icon' => 'fa-id-badge',
    'color' => '#0f766e',
    'url' => './biotime-administrativos/index.php',
    'enabled' => true,
  ],
  [
    'slug' => 'proyectos-milestones',
    'title' => 'PROYECTOS / Milestones',
    'description' => 'Vista de proyectos por milestone con porcentaje de avance, responsable, filtros de estatus y detalle por tareas.',
    'icon' => 'fa-diagram-project',
    'color' => '#3b82f6',
    'url' => './proyectos-milestones/index.php',
    'enabled' => true,
  ],

  // Ejemplos futuros:
  // [
  //     'slug' => 'inventario-rotacion',
  //     'title' => 'Inventario / Rotación',
  //     'description' => 'Rotación de inventario por periodo.',
  //     'icon' => 'fa-boxes-stacked',
  //     'color' => '#3b82f6',
  //     'url' => './inventario-rotacion/index.php',
  //     'enabled' => false,
  // ],
];
