<?php

declare(strict_types=1);

return [
  'titulo' => 'Produccion Monitoreo',
  'intervalo_actualizacion_ms' => 60000,
  'extraccion' => [
    'indicadores' => [
      'nivel_grasa' => [
        'label' => 'Nivel de grasa',
        'field' => 'NIVEL_TANQUE_DE_GRASA_DE_EXTRACCION',
        'unit' => '',
        'source' => 'sqlserver',
        'empty_label' => 'Sin dato',
      ],
    ],
  ],
  'secadores' => [
    'temperaturas_limite' => 0,
    'tuneles_placeholder' => [],
    'metricas' => [
      'velocidad_banda',
      'caudal_aire',
      'agua_caliente_suministro',
      'agua_caliente_retorno',
      'presion_vapor',
      'humedad_zona_1_inferior',
      'humedad_zona_2_inferior',
      'humedad_zona_3_inferior',
      'humedad_zona_4_inferior',
      'humedad_zona_5_inferior',
      'humedad_zona_6_inferior',
      'humedad_zona_7_inferior',
      'humedad_zona_8_inferior',
      'humedad_zona_9_inferior',
      'humedad_recamara_2',
      'humedad_recamara_4',
      'humedad_recamara_8',
      'humedad_suministro_aire',
    ],
    'votator_campos' => [
      'flujo',
      'presion_cuajado',
      'solidos',
      'amperaje_bomba',
      'amperaje_reductor',
    ],
    'votators_placeholder' => [
      'votator_5' => 'Votator 5',
      'votator_6' => 'Votator 6',
    ],
    'votator_mysql' => [
      'mysql_105' => [
        'host' => '192.168.1.105',
        'port' => 3306,
        'dbname' => 'progel_procesos',
        'user' => 'user_pro',
        'pass' => 'Pr0g3l2025PR',
        'charset' => 'utf8mb4',
        'timeout' => 3,
      ],
      'tabla_datos' => 'datos_producto',
      'columnas_orden' => ['id_datos_hora', 'id'],
      'columna_fo' => 'estado_fo_churro',
      'campos' => [
        'solidos' => [
          'label' => 'Sólidos',
          'field' => 'churro_solidos',
          'unit' => '%',
          'empty_label' => 'Sin dato',
          'semaforo' => [
            'modo' => 'minimo',
            'verde_min' => 34,
          ],
          'optimo_label' => '≥ 34 %',
        ],
      ],
    ],
    'votator_campos_overlay' => [
      'tunel_1' => [
        'votator_1' => [
          'campos' => [
            'amperaje_bomba' => [
              'label' => 'Amp bomba',
              'source' => 'sqlserver',
              'field' => 'CORRIENTE_DE_EXTRUSOR_V1_SA',
              'unit' => 'A',
              'available' => true,
              'empty_label' => 'Sin dato',
            ],
          ],
        ],
        'votator_2' => [
          'campos' => [
            'amperaje_bomba' => [
              'label' => 'Amp bomba',
              'source' => 'sqlserver',
              'field' => 'CORRIENTE_DE_EXTRUSOR',
              'unit' => 'A',
              'available' => true,
              'empty_label' => 'Sin dato',
            ],
          ],
        ],
      ],
      'tunel_2' => [
        'votator_5' => [
          'label' => 'Votator 5',
          'campos' => [
            'flujo' => [
              'label' => 'Flujo',
              'source' => 'sqlserver',
              'field' => 'flujo_votator_3',
              'unit' => '',
              'available' => true,
              'empty_label' => 'Sin dato',
              'semaforo' => [
                'modo' => 'bandas',
                'bandas' => [
                  ['max' => 10, 'estado' => 'rojo'],
                  ['min' => 10.5, 'max' => 11.499999, 'estado' => 'amarillo'],
                  ['min' => 11.5, 'max' => 12.5, 'estado' => 'verde'],
                  ['min' => 12.500001, 'max' => 13, 'estado' => 'amarillo'],
                  ['min' => 13, 'estado' => 'rojo'],
                ],
              ],
              'leyenda' => '11.5-12.5',
            ],
          ],
        ],
        'votator_6' => [
          'label' => 'Votator 6',
          'campos' => [
            'flujo' => [
              'label' => 'Flujo',
              'source' => 'sqlserver',
              'field' => 'FLujo_votator_4',
              'unit' => '',
              'available' => true,
              'empty_label' => 'Sin dato',
              'semaforo' => [
                'modo' => 'bandas',
                'bandas' => [
                  ['max' => 10, 'estado' => 'rojo'],
                  ['min' => 10.5, 'max' => 11.499999, 'estado' => 'amarillo'],
                  ['min' => 11.5, 'max' => 12.5, 'estado' => 'verde'],
                  ['min' => 12.500001, 'max' => 13, 'estado' => 'amarillo'],
                  ['min' => 13, 'estado' => 'rojo'],
                ],
              ],
              'leyenda' => '11.5-12.5',
            ],
          ],
        ],
      ],
    ],
    'votator_campos_extra' => [
      'flujo' => [
        'label' => 'Flujo',
        'unit' => '',
        'optimo_label' => 'Por definir',
      ],
      'presion_cuajado' => [
        'label' => 'Presión de cuajado',
        'unit' => 'kg/cm2',
        'rule' => [
          'verde_min' => 24,
          'verde_max' => 26,
        ],
      ],
      'solidos' => [
        'label' => 'Sólidos',
        'unit' => '%',
        'optimo_label' => 'Por definir',
      ],
      'amperaje_bomba' => [
        'label' => 'Amp bomba',
        'unit' => 'A',
        'optimo_label' => 'Por definir',
      ],
      'amperaje_reductor' => [
        'label' => 'Amp reductor',
        'unit' => 'A',
        'optimo_label' => 'Por definir',
      ],
    ],
  ],
  'cocedores' => [
    'mysql_105' => [
      'host' => '192.168.1.105',
      'port' => 3306,
      'dbname' => 'progel_procesos',
      'user' => 'user_pro',
      'pass' => 'Pr0g3l2025PR',
      'charset' => 'utf8mb4',
      'timeout' => 3,
    ],
    'tabla_datos' => 'datos_cocedores',
    'columna_numero' => 'numero_cocedor',
    'columna_fo' => 'estado_fo',
    'columnas_orden' => ['id_datos_hora', 'id'],
    'encabezado' => [
      'temperatura_entrada' => [
        'label' => 'Entrada',
        'field' => 'COCEDORES_TEMPERATURA_DE_ENTRADA',
        'unit' => '°C',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 60,
          'verde_max' => 68,
          'amarillo_min' => 59,
          'amarillo_max' => 69,
        ],
        'leyenda' => '60-68 °C',
      ],
      'temperatura_salida' => [
        'label' => 'Salida',
        'field' => 'COCEDORES_TEMPERATURA_DE_SALIDA',
        'unit' => '°C',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 55,
          'verde_max' => 63,
          'amarillo_min' => 54,
          'amarillo_max' => 64,
        ],
        'leyenda' => '55-63 °C',
      ],
    ],
    'metricas_mysql' => [
      'ntu' => [
        'label' => 'NTU',
        'field' => 'ntu',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 60,
          'verde_max' => 600,
          'amarillo_min' => 50,
          'amarillo_max' => 610,
        ],
        'leyenda' => '60-600',
      ],
      'solidos' => [
        'label' => 'Sólidos',
        'field' => 'solidos',
        'unit' => '%',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 2.5,
          'verde_max' => 3.5,
          'amarillo_min' => 2.3,
          'amarillo_max' => 3.7,
        ],
        'leyenda' => '2.5-3.5 %',
      ],
      'ph' => [
        'label' => 'pH',
        'field' => 'ph',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 3,
          'verde_max' => 3.8,
          'amarillo_min' => 2.9,
          'amarillo_max' => 3.9,
        ],
        'leyenda' => '3-3.8',
      ],
    ],
    'equipos' => [
    'cocedor_1' => [
      'titulo' => 'Cocedor 1',
      'flujo_field' => 'Flujo_cocedor_1',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 150,
        'verde_max' => 155,
        'amarillo_min' => 149,
        'amarillo_max' => 156,
      ],
      'flujo_leyenda' => '150-155',
    ],
    'cocedor_2' => [
      'titulo' => 'Cocedor 2',
      'flujo_field' => 'Flujo_cocedor_2',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 150,
        'verde_max' => 155,
        'amarillo_min' => 149,
        'amarillo_max' => 156,
      ],
      'flujo_leyenda' => '150-155',
    ],
    'cocedor_3' => [
      'titulo' => 'Cocedor 3',
      'flujo_field' => 'Flujo_cocedor_3',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 150,
        'verde_max' => 155,
        'amarillo_min' => 149,
        'amarillo_max' => 156,
      ],
      'flujo_leyenda' => '150-155',
    ],
    'cocedor_4' => [
      'titulo' => 'Cocedor 4',
      'flujo_field' => 'Flujo_cocedor_4',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 150,
        'verde_max' => 155,
        'amarillo_min' => 149,
        'amarillo_max' => 156,
      ],
      'flujo_leyenda' => '150-155',
    ],
    'cocedor_5' => [
      'titulo' => 'Cocedor 5',
      'flujo_field' => 'Flujo_cocedor_5',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 150,
        'verde_max' => 155,
        'amarillo_min' => 149,
        'amarillo_max' => 156,
      ],
      'flujo_leyenda' => '150-155',
    ],
    'cocedor_6' => [
      'titulo' => 'Cocedor 6',
      'flujo_field' => 'Flujo_cocedor_6',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 170,
        'verde_max' => 175,
        'amarillo_min' => 169,
        'amarillo_max' => 176,
      ],
      'flujo_leyenda' => '170-175',
    ],
    'cocedor_7' => [
      'titulo' => 'Cocedor 7',
      'flujo_field' => 'Flujo_cocedor_7',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 170,
        'verde_max' => 175,
        'amarillo_min' => 169,
        'amarillo_max' => 176,
      ],
      'flujo_leyenda' => '170-175',
    ],
    'cocedor_8' => [
      'titulo' => 'Cocedor 8',
      'flujo_field' => 'FLUJO_COCEDOR_8',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 170,
        'verde_max' => 175,
        'amarillo_min' => 169,
        'amarillo_max' => 176,
      ],
      'flujo_leyenda' => '170-175',
    ],
    'cocedor_9' => [
      'titulo' => 'Cocedor 9',
      'flujo_field' => 'FLUJO_COCEDOR_9',
      'flujo_semaforo' => [
        'modo' => 'rango',
        'verde_min' => 170,
        'verde_max' => 175,
        'amarillo_min' => 169,
        'amarillo_max' => 176,
      ],
      'flujo_leyenda' => '170-175',
    ],
    ],
  ],
  'clarificadores' => [
    'key' => 'clarificador',
    'titulo' => 'Clarificador',
    'mysql_105' => [
      'host' => '192.168.1.105',
      'port' => 3306,
      'dbname' => 'progel_procesos',
      'user' => 'user_pro',
      'pass' => 'Pr0g3l2025PR',
      'charset' => 'utf8mb4',
      'timeout' => 3,
    ],
    'tabla_datos' => 'datos_clarificador',
    'columna_fo' => 'estado_fo',
    'columnas_orden' => ['id_datos_hora', 'id'],
    'sqlserver' => [
      'tabla' => 'TREND001',
      'campo_fecha' => 'Time_Stamp',
    ],
    'metricas' => [
      'solidos' => [
        'label' => 'Sólidos',
        'field' => 'solidos',
        'unit' => '%',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 2.5,
          'verde_max' => 3.5,
          'amarillo_min' => 2.3,
          'amarillo_max' => 3.7,
        ],
        'leyenda' => '2.5-3.5 %',
      ],
      'temperatura' => [
        'label' => 'Temperatura',
        'field' => 'temperatura',
        'unit' => '°C',
      ],
      'flujo' => [
        'label' => 'Flujo',
        'field' => 'flujo',
        'unit' => '',
      ],
      'flujo_polimero' => [
        'label' => 'Flujo Polímero',
        'source' => 'sqlserver',
        'field' => 'FLUJO_POLIMERO_CLARIFICADOR',
        'unit' => '',
      ],
      'ntu_entrada' => [
        'label' => 'NTU Entrada',
        'field' => 'ntu_entrada',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 50,
          'verde_max' => 600,
          'amarillo_min' => 40,
          'amarillo_max' => 610,
        ],
        'leyenda' => '50-600',
      ],
      'ntu_salida' => [
        'label' => 'NTU Salida',
        'field' => 'ntu_salida',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 5,
          'verde_max' => 12,
          'amarillo_min' => 4,
          'amarillo_max' => 13,
        ],
        'leyenda' => '5-12',
      ],
      'ph_entrada' => [
        'label' => 'pH Entrada',
        'field' => 'ph_entrada',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 3,
          'verde_max' => 3.8,
          'amarillo_min' => 2.9,
          'amarillo_max' => 3.9,
        ],
        'leyenda' => '3-3.8',
      ],
      'ph_electrodo' => [
        'label' => 'pH Electrodo',
        'field' => 'ph_electrodo',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 5.5,
          'verde_max' => 6.5,
          'amarillo_min' => 5.3,
          'amarillo_max' => 6.7,
        ],
        'leyenda' => '5.5-6.5',
      ],
      'ph_salida' => [
        'label' => 'pH Salida',
        'field' => 'ph_salida',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 5.5,
          'verde_max' => 6.5,
          'amarillo_min' => 5.3,
          'amarillo_max' => 6.7,
        ],
        'leyenda' => '5.5-6.5',
      ],
      'ce_salida' => [
        'label' => 'CE Salida',
        'field' => 'ce_salida',
        'unit' => '',
        'semaforo' => [
          'modo' => 'maximo',
          'verde_max' => 6.49,
          'amarillo_max' => 6.69,
        ],
        'leyenda' => '< 6.5',
      ],
      'mez_balance' => [
        'label' => 'Mez Balance',
        'field' => 'mez_balance',
        'unit' => '',
      ],
    ],
  ],
  'integracion' => [
    'key' => 'integracion',
    'titulo' => 'Integración',
    'mysql_105' => [
      'host' => '192.168.1.105',
      'port' => 3306,
      'dbname' => 'progel_procesos',
      'user' => 'user_pro',
      'pass' => 'Pr0g3l2025PR',
      'charset' => 'utf8mb4',
      'timeout' => 3,
    ],
    'tabla_datos' => 'datos_filtracion_integracion',
    'columna_fo' => 'estado_fo_integ',
    'columnas_orden' => ['id_datos_hora', 'id'],
    'metricas' => [
      'visc_integracion' => [
        'label' => 'VISCOSIDAD',
        'field' => 'integ_viscosidad',
        'unit' => '',
        'semaforo' => [
          'modo' => 'minimo',
          'verde_min' => 25.01,
        ],
        'leyenda' => '> 25',
      ],
      'flujo_integracion' => [
        'label' => 'FLUJO',
        'field' => 'integ_flujo',
        'unit' => '',
        'semaforo' => [
          'modo' => 'rango',
          'verde_min' => 2,
          'verde_max' => 5,
          'amarillo_min' => 1.5,
          'amarillo_max' => 5.5,
        ],
        'leyenda' => '2-5',
      ],
    ],
  ],
];
