<?php

declare(strict_types=1);

return [
  'titulo' => 'Reporte de Finanzas',
  'subtitulo' => 'Resumen mensual de gastos, fabricación y venta',
  'timezone' => 'America/Mexico_City',
  'api_facturas_compra' => [
    'url' => 'http://192.168.1.104:5000/api/facturas-compra',
    'query_parameter' => 'cvde1',
    'response_field' => 'cvede1',
    'clasificaciones' => [
      'produccion' => [102],
      'financiero' => [3, 20],
      'materia_prima_nacional' => [452],
      'materia_prima_internacional' => [453],
    ],
    'timeout' => 30,
    'cache_ttl' => 900,
    'cache_version' => 5,
  ],
  'gastos' => [
    'materia_prima_nacional' => [
      'label' => 'Materia prima nacional',
      'icon' => 'fa-boxes-stacked',
      'source' => 'api_facturas_compra',
      'source_detail' => 'Clave 452 · cvde7',
    ],
    'materia_prima_internacional' => [
      'label' => 'Materia prima internacional',
      'icon' => 'fa-earth-americas',
      'source' => 'api_facturas_compra',
      'source_detail' => 'Clave 453 · cvde7',
    ],
    'quimicos' => ['label' => 'Químicos', 'icon' => 'fa-flask'],
    'produccion' => ['label' => 'Producción', 'icon' => 'fa-industry', 'source' => 'api_facturas_compra'],
    'venta' => ['label' => 'Venta', 'icon' => 'fa-cart-shopping'],
    'laboral' => ['label' => 'Laboral', 'icon' => 'fa-people-group'],
    'financieros' => [
      'label' => 'Financiero',
      'icon' => 'fa-building-columns',
      'source' => 'api_facturas_compra',
      'source_detail' => 'Compras (3) + Contabilidad (20)',
    ],
  ],
  'departamentos' => [
    ['code' => 1, 'label' => 'Dirección'],
    ['code' => 2, 'label' => 'Almacén'],
    ['code' => 3, 'label' => 'Compras'],
    ['code' => 4, 'label' => 'Calidad'],
    ['code' => 5, 'label' => 'Control eléctrico'],
    ['code' => 6, 'label' => 'Ecología'],
    ['code' => 7, 'label' => 'Mantenimiento preventivo'],
    ['code' => 8, 'label' => 'Mantenimiento correctivo'],
    ['code' => 9, 'label' => 'Nuevos proyectos'],
    ['code' => 10, 'label' => 'Seguridad e higiene'],
    ['code' => 11, 'label' => 'Sistemas'],
    ['code' => 12, 'label' => 'Recursos humanos'],
    ['code' => 13, 'label' => 'Ventas'],
    ['code' => 14, 'label' => 'Revolturas'],
    ['code' => 15, 'label' => 'Producción'],
    ['code' => 16, 'label' => 'Preparación'],
    ['code' => 17, 'label' => 'Comedor'],
    ['code' => 18, 'label' => 'Estadística'],
    ['code' => 19, 'label' => 'Materia prima'],
    ['code' => 20, 'label' => 'Contabilidad'],
    ['code' => 21, 'label' => 'Oficinas 2'],
    ['code' => 100, 'label' => 'Ecología'],
    ['code' => 101, 'label' => 'Preparación'],
    ['code' => 102, 'label' => 'Producción'],
    ['code' => 103, 'label' => 'Revolturas y empaques'],
    ['code' => 104, 'label' => 'Aseguramiento de la calidad'],
    ['code' => 105, 'label' => 'Energéticos'],
    ['code' => 106, 'label' => 'Combustibles'],
    ['code' => 107, 'label' => 'Sistemas'],
    ['code' => 108, 'label' => 'Comedor'],
    ['code' => 109, 'label' => 'Recursos humanos'],
    ['code' => 110, 'label' => 'Seguridad e higiene'],
    ['code' => 111, 'label' => 'Infraestructura'],
    ['code' => 112, 'label' => 'Mantenimiento'],
    ['code' => 113, 'label' => 'Gestión'],
    ['code' => 114, 'label' => 'Servicio médico'],
    ['code' => 115, 'label' => 'Seguridad patrimonial'],
    ['code' => 116, 'label' => 'Ventas'],
    ['code' => 117, 'label' => 'Compras'],
    ['code' => 118, 'label' => 'Almacén'],
    ['code' => 119, 'label' => 'Administración y contabilidad'],
    ['code' => 120, 'label' => 'Pelambre'],
    ['code' => 121, 'label' => 'Investigación y desarrollo'],
    ['code' => 122, 'label' => 'Mejora continua'],
    ['code' => 123, 'label' => 'Nuevos proyectos'],
  ],
  'indicadores' => [
    'costo_fabricacion' => ['label' => 'Costo de fabricación', 'icon' => 'fa-gears'],
    'precio_promedio_venta' => ['label' => 'Precio promedio de venta', 'icon' => 'fa-tags'],
  ],
];
